language: python
python:
  - "3.4"
  - "3.5"

install: "pip install -r requirements.txt"
script: nosetests
#script:
#  - coverage run --rcfile=.coveragerc --source=linear_solver setup.py test
#after_success:
#  - coveralls
